version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: changeme#rooot
      MYSQL_DATABASE: erm_wiki
      MYSQL_USER: erm_wiki
      MYSQL_PASSWORD: changeme#appuser
  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: erm_wiki
      DB_NAME: erm_wiki
      DB_PASS: changeme#appuser
    restart: unless-stopped
    ports:
      - '8081:3000'

volumes:
  db_data:
